// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhtaXgJGMmpzco8PVa8fl_z-ZuEOWfRac',
    appId: '1:251988802186:web:425a538903c6642926cb73',
    messagingSenderId: '251988802186',
    projectId: 'my-first-project-3ecc7',
    authDomain: 'my-first-project-3ecc7.firebaseapp.com',
    storageBucket: 'my-first-project-3ecc7.firebasestorage.app',
    measurementId: 'G-BQ519Y9L9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Fx-yMcrdO7XKVZywuwQqwDu05hW2TjU',
    appId: '1:251988802186:android:9c31c5debd855c3926cb73',
    messagingSenderId: '251988802186',
    projectId: 'my-first-project-3ecc7',
    storageBucket: 'my-first-project-3ecc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbY7084d6FeimlhOqaoqHe2ajaQXu4WW0',
    appId: '1:251988802186:ios:75136f79f13d64b326cb73',
    messagingSenderId: '251988802186',
    projectId: 'my-first-project-3ecc7',
    storageBucket: 'my-first-project-3ecc7.firebasestorage.app',
    iosClientId: '251988802186-vnp9od43pofp7on9i5dkarptn7las76k.apps.googleusercontent.com',
    iosBundleId: 'com.example.booksApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbY7084d6FeimlhOqaoqHe2ajaQXu4WW0',
    appId: '1:251988802186:ios:75136f79f13d64b326cb73',
    messagingSenderId: '251988802186',
    projectId: 'my-first-project-3ecc7',
    storageBucket: 'my-first-project-3ecc7.firebasestorage.app',
    iosClientId: '251988802186-vnp9od43pofp7on9i5dkarptn7las76k.apps.googleusercontent.com',
    iosBundleId: 'com.example.booksApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhtaXgJGMmpzco8PVa8fl_z-ZuEOWfRac',
    appId: '1:251988802186:web:c8a4451b4ea3d44f26cb73',
    messagingSenderId: '251988802186',
    projectId: 'my-first-project-3ecc7',
    authDomain: 'my-first-project-3ecc7.firebaseapp.com',
    storageBucket: 'my-first-project-3ecc7.firebasestorage.app',
    measurementId: 'G-27WXG28Q6V',
  );

}